let npcs = [
    'DeleteEntity',
    'Gentari',
    'Festari',
    'ForestMinish',
    'Postman',
    'NPC5',
    'Townsperson',
    'Kid',
    'Guard',
    'NPC9',
    'Stamp',
    'Maid',
    'Marcy',
    'Wheaton',
    'Pita',
    'MinishEzlo',
    'Mailbox',
    'Beedle',
    'Brocco',
    'SittingPerson',
    'Pina',
    'Guard',
    'Maid',
    'Din',
    'Nayru',
    'Farore',
    'Sturgeon',
    'TingleSiblings',
    'Stockwell',
    'Talon',
    'Malon',
    'Epona',
    'MilkCart',
    'GhostBrothers',
    'Smith',
    'NPC23',
    'KingDaltus',
    'MinisterPotho',
    'NPC26',
    'Vaati',
    'Zelda',
    'Mutoh',
    'Carpenter',
    'CastorWildsStatue',
    'Cat',
    'MountainMinish',
    'ZeldaFollower',
    'Melari',
    'BladeBrothers',
    'Cow',
    'Goron',
    'GoronMerchant',
    'Gorman',
    'Dog',
    'Syrup',
    'Rem',
    'TownMinish',
    'Librari',
    'Percy',
    'VaatiReborn',
    'MoblinLady',
    'Librarians',
    'Farmers',
    'Carlov',
    'Dampe',
    'DrLeft',
    'KingGustaf',
    'Gina',
    'Simon',
    'Anju',
    'Mama',
    'Emma',
    'Teachers',
    'WindTribespeople',
    'Gregal',
    'MayorHagen',
    'BigGoron',
    'EzloCap',
    'NPC4E',
    'NPC4F',
    'ClothesRack',
    'PicolyteBottle',
    'SmallTownMinish',
    'HurdyGurdyMan',
    'Cucco',
    'CuccoChick',
    'FusionMenuNPC',
    'Phonograph',
    'NPC58',
    ]

let enemies= [
    'OCTOROK',
    'CHUCHU',
    'LEEVER',
    'PEAHAT',
    'ROLLOBITE',
    'DARK_NUT',
    'HANGING_SEED',
    'BEETLE',
    'KEESE',
    'DOOR_MIMIC',
    'ROCK_CHUCHU',
    'SPINY_CHUCHU',
    'CUCCO_CHICK_AGGR',
    'MOLDORM',
    'ENEMY_E',
    'MOLDWORM',
    'SLUGGULA',
    'PESTO',
    'PUFFSTOOL',
    'CHUCHU_BOSS',
    'LIKE_LIKE',
    'SPEAR_MOBLIN',
    'BUSINESS_SCRUB',
    'RUPEE_LIKE',
    'MADDERPILLAR',
    'WATER_DROP',
    'WALL_MASTER',
    'BOMB_PEAHAT',
    'SPARK',
    'CHASER',
    'SPIKED_BEETLE',
    'SENSOR_BLADE_TRAP',
    'HELMASAUR',
    'FALLING_BOULDER',
    'BOBOMB',
    'WALL_MASTER_2',
    'GLEEROCK',
    'VAATI_EYES_MACRO',
    'TEKTITE',
    'WIZZROBE_WIND',
    'WIZZROBE_FIRE',
    'WIZZROBE_ICE',
    'ARMOS',
    'EYEGORE',
    'ROPE',
    'SMALL_PESTO',
    'ACRO_BANDIT',
    'BLADE_TRAP',
    'KEATON',
    'CROW',
    'MULLDOZER',
    'BOMBAROSSA',
    'WISP',
    'SPINY_BEETLE',
    'MAZAAL_HEAD',
    'MAZAAL_MACRO',
    'MAZAAL_HAND',
    'OCTOROK_BOSS',
    'FLYING_POT',
    'GOBDO',
    'OCTOROK_GOLDEN',
    'TEKTITE_GOLDEN',
    'ROPE_GOLDEN',
    'CLOUD_PIRANHA',
    'SCISSORS_BEETLE',
    'CUCCO_AGGR',
    'STALFOS',
    'FLYING_SKULL',
    'MAZAAL_BRACELET',
    'TAKKURI',
    'BOW_MOBLIN',
    'LAKITU',
    'LAKITU_CLOUD',
    'ENEMY_49',
    'VAATI_REBORN_ENEMY',
    'VAATI_PROJECTILE',
    'BALL_CHAIN_SOLIDER',
    'ENEMY_4D',
    'GHINI',
    'VAATI_TRANSFIGURED',
    'ENEMY_50',
    'VAATI_WRATH',
    'VAATI_ARM',
    'DUST',
    'VAATI_BALL',
    'OCTOROK2',
    'SLIME',
    'MINI_SLIME',
    'FIREBALL_GUY',
    'MINI_FIREBALL_GUY',
    'ENEMY_5A',
    'BUSINESS_SCRUB_PROLOGUE',
    'GYORG_FEMALE',
    'GYORG_MALE',
    'CURTAIN',
    'ENEMY_5F',
    'GYORG_CHILD',
    'GYORG_FEMALE_EYE',
    'ENEMY_62',
    'GYORG_FEMALE_MOUTH',
    'ENEMY_64',
    'TREE_ITEM',
    'ENEMY_66'
    ]

let objects = [
    'GROUND_ITEM',
    'DEATH_FX',
    'SHOP_ITEM',
    'BUTTON',
    'OBJECT_4',
    'POT',
    'OBJECT_6',
    'PUSHED_BLOCK',
    'LOCKED_DOOR',
    'OBJECT_9',
    'OBJECT_A',
    'OBJECT_B',
    'CHEST_SPAWNER',
    'OBJECT_D',
    'OBJECT_E',
    'SPECIAL_FX',
    'OBJECT_10',
    'OBJECT_11',
    'OBJECT_12',
    'RAILTRACK',
    'LILYPAD_LARGE',
    'OBJECT_15',
    'FLOATING_PLATFORM',
    'OBJECT_17',
    'EVIL_SPIRIT',
    'HOUSE_DOOR_EXT',
    'OBJECT_1A',
    'GREAT_FAIRY',
    'OBJECT_1C',
    'OBJECT_1D',
    'OBJECT_1E',
    'OBJECT_1F',
    'OBJECT_20',
    'OBJECT_21',
    'FIGURINE_DEVICE',
    'EYE_SWITCH',
    'OBJECT_24',
    'BIG_BARREL',
    'OBJECT_26',
    'PUSHABLE_STATUE',
    'OBJECT_28',
    'OBJECT_29',
    'OBJECT_2A',
    'OBJECT_2B',
    'BEANSTALK',
    'SMOKE',
    'PUSHABLE_ROCK',
    'HITTABLE_LEVER',
    'OBJECT_30',
    'FROZEN_FLOWER',
    'PULLABLE_MUSHROOM',
    'BOLLARD',
    'WARP_POINT',
    'OBJECT_35',
    'OBJECT_36',
    'OBJECT_37',
    'JAR_PORTAL',
    'BOSS_DOOR',
    'OBJECT_3A',
    'PORTAL_MUSHROOM_STALKS',
    'PORTAL_FALLING_PLAYER',
    'OBJECT_3D',
    'OBJECT_3E',
    'GIANT_LEAF',
    'FAIRY',
    'LADDER_UP',
    'OBJECT_42',
    'OBJECT_43',
    'OBJECT_44',
    'OBJECT_45',
    'GIANT_BOOK_LADDER',
    'HEART_CONTAINER',
    'FILE_SCREEN_OBJECTS',
    'OBJECT_49',
    'BACKGROUND_CLOUD',
    'OBJECT_4B',
    'PUSHABLE_FURNITURE',
    'FURNITURE',
    'MINISH_SIZED_ENTRANCE',
    'ARCHWAY',
    'GIANT_ROCK',
    'OBJECT_51',
    'OBJECT_52',
    'OBJECT_53',
    'PULLABLE_LEVER',
    'MINECART',
    'THOUGHT_BUBBLE',
    'HIDDEN_LADDER_DOWN',
    'GENTARI_CURTAIN',
    'LAVA_PLATFORM',
    'OBJECT_5A',
    'OBJECT_5B',
    'MASK',
    'HOUSE_DOOR_INT',
    'WHIRLWIND',
    'OBJECT_BLOCKING_STAIRS',
    'SWORDSMAN_NEWSLETTER',
    'OBJECT_61',
    'GIANT_TWIG',
    'OBJECT_63',
    'OBJECT_64',
    'LADDER_HOLE',
    'OBJECT_66',
    'OBJECT_67',
    'OBJECT_68',
    'OBJECT_69',
    'OBJECT_6A',
    'CRENAL_BEAN_SPROUT',
    'MINECART_DOOR',
    'OBJECT_ON_PILLAR',
    'MINERAL_WATER_SOURCE',
    'MINISH_SIZED_ARCHWAY',
    'OBJECT_70',
    'PUSHABLE_GRAVE',
    'OBJECT_72',
    'LILYPAD_SMALL',
    'OBJECT_74',
    'OBJECT_75',
    'OBJECT_76',
    'BELL',
    'HUGE_DECORATION',
    'OBJECT_79',
    'STEAM',
    'PUSHABLE_LEVER',
    'HUGE_SHOES',
    'OBJECT_ON_BEETLE',
    'OBJECT_7E',
    'PICO_BLOOM',
    'OBJECT_80',
    'OBJECT_81',
    'BIG_VORTEX',
    'BIG_PUSHABLE_LEVER',
    'SMALL_ICE_BLOCK',
    'BIG_ICE_BLOCK',
    'OBJECT_86',
    'OBJECT_87',
    'HUGE_BOOK',
    'OBJECT_89',
    'OBJECT_8A',
    'OBJECT_8B',
    'BOOK',
    'FIREPLACE',
    'OBJECT_8E',
    'FROZEN_WATER_ELEMENT',
    'OBJECT_90',
    'OBJECT_91',
    'BAKER_OVEN',
    'OBJECT_93',
    'WIND_TRIBE_FLAG',
    'BIRD',
    'OBJECT_96',
    'OBJECT_97',
    'OBJECT_98',
    'OBJECT_99',
    'HUGE_ACORN',
    'OBJECT_9B',
    'TREE_HIDING_PORTAL',
    'LIGHTABLE_SWITCH',
    'OBJECT_9E',
    'FAN',
    'OBJECT_A0',
    'PALACE_ARCHWAY',
    'OBJECT_A2',
    'CLOUD',
    'MINISH_LIGHT',
    'OBJECT_A5',
    'OBJECT_A6',
    'OBJECT_A7',
    'OBJECT_A8',
    'OBJECT_A9',
    'WATERFALL_OPENING',
    'OBJECT_AB',
    'FOUR_ELEMENTS',
    'OBJECT_AD',
    'FLOATING_BLOCK',
    'OBJECT_AF',
    'METAL_DOOR',
    'JAIL_BARS',
    'OBJECT_B2',
    'OBJECT_B3',
    'OBJECT_B4',
    'OBJECT_B5',
    'OBJECT_B6',
    'WELL',
    'WIND_TRIBE_TELEPORTER',
    'OBJECT_B9',
    'OBJECT_BA',
    'WINDCREST',
    'LIT_AREA',
    'OBJECT_BD',
    'PINWHEEL',
    'OBJECT_BF',
    'ENEMY_ITEM',
    'OBJECT_C1',
    ]

let globalFlags = [
    'FLAG_NONE',
    'LV0_CLEAR',
    'LV1_CLEAR',
    'LV2_CLEAR',
    'LV3_CLEAR',
    'LV4_CLEAR',
    'LV5_CLEAR',
    'LV6_CLEAR',
    'LV7_CLEAR',
    'LV8_CLEAR',
    'MACHI_SET_1 Defeated Big Green Chuchu',
    'MACHI_SET_2 Defeated Gleerok',
    'MACHI_SET_3',
    'MACHI_SET_4 Defeated Big Octorok',
    'MACHI_SET_5 Defeated Gyorg Pair',
    'MACHI_SET_6',
    'MACHI_SET_7',
    'MACHI_SET_8',
    'MACHI_MACHIHOKORI Sucked dust from carpet',
    'START Met Zelda',
    'EZERO_1ST Met Ezlo',
    'TABIDACHI Talked to Daltus and Smith',
    'LV1TARU',
    'LV1TARU_OPEN Sucked barrel web',
    'TATEKAKE_HOUSE Red house complete',
    'TATEKAKE_TOCHU Red house frame',
    'WATERBEAN_OUT Holding bean',
    'WATERBEAN_PUT Threw bean in hole',
    'ZELDA_CHASE Enter town festival',
    'INLOCK Gave key to Talon',
    'DASHBOOTS Read Castor Wilds sign',
    'LEFT_DOOR_OPEN Spoke to Dr. Left',
    'HAKA_KEY_LOST Graveyard key stolen',
    'HAKA_KEY_FOUND Graveyard key obtained back',
    'ENTRANCE_OK',
    'TATSUMAKI',
    'KUMOTATSUMAKI Vortex spawned',
    'KAITENGIRI',
    'DAIKAITENGIRI',
    'GATOTSU',
    'KABUTOWARI',
    'MIZUKAKI_START Spoke to Lake Hylia Minish',
    'MIZUKAKI_HARIFALL Library book falling',
    'RENTED_HOUSE_DIN Din moves to blue house',
    'RENTED_HOUSE_NAYRU Nayru moves to blue house',
    'RENTED_HOUSE_FARORE Farore moves to blue house',
    'NEW_HOUSE_DIN Din moves to red house',
    'NEW_HOUSE_NAYRU Nayru moves to red house',
    'NEW_HOUSE_FARORE Farore moves to red house',
    'OUGONTEKI_A Golden Octorok defeated',
    'OUGONTEKI_B Golden Tektite defeated',
    'OUGONTEKI_C Golden Rope defeated',
    'OUGONTEKI_D Golden Rope defeated',
    'OUGONTEKI_E Golden Rope defeated',
    'OUGONTEKI_F Golden Tektite defeated',
    'OUGONTEKI_G Golden Tektite defeated',
    'OUGONTEKI_H Golden Octorok defeated',
    'OUGONTEKI_I Golden Octorok defeated',
    'KAKERA_COMPLETE All fusions complete',
    'DRUG_1 Yellow pico bloomed',
    'DRUG_2 Blue pico bloomed',
    'DRUG_3 Orange pico bloomed',
    'GORON_KAKERA_LV2 Goron merchant restock 1',
    'GORON_KAKERA_LV3 Goron merchant restock 2',
    'GORON_KAKERA_LV4 Goron merchant restock 3',
    'GORON_KAKERA_LV5 Goron merchant restock 4',
    'GORON_KAKERA_L Red kinstone sold out',
    'GORON_KAKERA_M Blue kinstone sold out',
    'GORON_KAKERA_R Green kinstone sold out',
    'CHIKATSURO_SHUTTER Castle basement door open',
    'ENTRANCE_USED',
    'GOMAN_RENTED_HOUSE Spoke to Gorman blue house',
    'GOMAN_NEW_HOUSE Spoke to Gorman red house',
    'OUTDOOR Exited Link\'s house',
    'POWERGLOVE_HINT Spoke to Dr. Left Minish',
    'ANJU_LV_BIT0 Cucco game 1 bit',
    'ANJU_LV_BIT1 Cucco game 2 bit',
    'ANJU_LV_BIT2 Cucco game 4 bit',
    'ANJU_LV_BIT3 Cucco game 8 bit',
    'ANJU_HEART Cucco heart piece',
    'MAROYA_WAKEUP',
    'ENDING Vaati\'s wrath defeated',
    'WARP_1ST Wind ocarina unlocked',
    'WARP_MONUMENT First windcrest discovered',
    'DRUG_COUNT Pico bloom minish items',
    'GAMECLEAR Watched end cutscene',
    'WHITE_SWORD_END Exit mines with white sword',
    'SOUGEN_06_HASHIGO Boomerang cave ladder',
    'WARP_EVENT_END Wind tribe tower state',
    'FIGURE_ALLCOMP Obtained Carlov Medal',
    'AKINDO_BOTTLE_SELL Bought bottle from scrub',
    'BIN_DOGFOOD',
    'TINGLE_TALK1ST Spoke to Tingle',
    'SEIIKI_BGM Elemental sanctuary BGM',
    'ENTRANCE_0 Trunk entrance cutscene',
    'ENTRANCE_1 Rock entrance cutscene',
    'ENTRANCE_2 Pot entrance cutscene',
    'MIZUKAKI_NECHAN Spoke to librarian',
    'MAZE_CLEAR Cleared Castle maze',
    'TINY_ENTRANCE Ezlo described entrances',
    'CASTLE_BGM Castle intro BGM',
];

let projectiles = [
    'DarkNutSwordSlash',
    'RockProjectile',
    '0x2',
    'MoblinSpear',
    'DekuSeedProjectile',
    '0x5',
    'DirtBallProjectile',
    'WindProjectile',
    'FireProjectile',
    'IceProjectile',
    'GleerokProjectile',
    'KeatonDagger',
    'GuardLineOfSight',
    'ArrowProjectile',
    'MazaalEnergyBeam',
    'OctorokBossProjectile',
    '0x10',
    'LakituCloud',
    'LakituLightning',
    'MandiblesProjectile',
    'RemovableDust',
    'SpiderWeb',
    'TorchTrapProjectile',
    'GuruguruBarProjectile',
    '0x18',
    'BallAndChain',
    '0x1a',
    'CannonballProjectile',
    '0x1c',
    'Winder',
    'SpikedRollers',
    '0x1f',
    '0x20',
    '0x21',
    '0x22',
    '0x23',
    '0x24'
];

export {
    npcs,
    enemies,
    objects,
    globalFlags,
    projectiles
}